package twilightforest.world.components.structures.courtyard;

import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Rotation;
import net.minecraft.world.level.levelgen.structure.pieces.StructurePieceSerializationContext;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager;
import twilightforest.TwilightForestMod;
import twilightforest.init.TFStructurePieceTypes;

public class NagaCourtyardHedgeIntersectionComponent extends NagaCourtyardHedgeAbstractComponent {
	public NagaCourtyardHedgeIntersectionComponent(StructurePieceSerializationContext ctx, CompoundTag nbt) {
		super(ctx, TFStructurePieceTypes.TFNCIs.get(), nbt, TwilightForestMod.prefix("courtyard/hedge_intersection"), TwilightForestMod.prefix("courtyard/hedge_intersection_big"));
	}

	public NagaCourtyardHedgeIntersectionComponent(StructureTemplateManager manager, int i, int x, int y, int z, Rotation rotation) {
		super(manager, TFStructurePieceTypes.TFNCIs.get(), i, x, y, z, rotation, TwilightForestMod.prefix("courtyard/hedge_intersection"), TwilightForestMod.prefix("courtyard/hedge_intersection_big"));
	}
}
