package twilightforest.worldgen;

import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.HugeMushroomBlock;
import twilightforest.block.TFBlocks;

public final class BlockConstants {
    //Blockstates
    public static final BlockState SPRUCE_LOG = Blocks.SPRUCE_LOG.getDefaultState();
    public static final BlockState SPRUCE_LEAVES = Blocks.SPRUCE_LEAVES.getDefaultState();
    public static final BlockState JUNGLE_LOG = Blocks.JUNGLE_LOG.getDefaultState();
    public static final BlockState OAK_LEAVES = Blocks.OAK_LEAVES.getDefaultState();
    public static final BlockState TOAK_LOG = TFBlocks.oak_log.get().getDefaultState();
    public static final BlockState TOAK_WOOD = TFBlocks.oak_wood.get().getDefaultState();
    public static final BlockState TOAK_LEAVES = TFBlocks.oak_leaves.get().getDefaultState();
    public static final BlockState CANOPY_LOG = TFBlocks.canopy_log.get().getDefaultState();
    public static final BlockState CANOPY_LEAVES = TFBlocks.canopy_leaves.get().getDefaultState();
    public static final BlockState MANGROVE_LOG = TFBlocks.mangrove_log.get().getDefaultState();
    public static final BlockState MANGROVE_WOOD = TFBlocks.mangrove_wood.get().getDefaultState();
    public static final BlockState MANGROVE_LEAVES = TFBlocks.mangrove_leaves.get().getDefaultState();
    public static final BlockState DARKWOOD_LOG = TFBlocks.dark_log.get().getDefaultState();
    public static final BlockState DARKWOOD_LEAVES = TFBlocks.dark_leaves.get().getDefaultState();
    public static final BlockState TIME_LOG = TFBlocks.time_log.get().getDefaultState();
    public static final BlockState TIME_WOOD = TFBlocks.time_wood.get().getDefaultState();
    public static final BlockState TIME_LEAVES = TFBlocks.time_leaves.get().getDefaultState();
    public static final BlockState TRANSFORM_LOG = TFBlocks.transformation_log.get().getDefaultState();
    public static final BlockState TRANSFORM_LEAVES = TFBlocks.transformation_leaves.get().getDefaultState();
    public static final BlockState MINING_LOG = TFBlocks.mining_log.get().getDefaultState();
    public static final BlockState MINING_WOOD = TFBlocks.mining_wood.get().getDefaultState();
    public static final BlockState MINING_LEAVES = TFBlocks.mining_leaves.get().getDefaultState();
    public static final BlockState SORT_LOG = TFBlocks.sorting_log.get().getDefaultState();
    public static final BlockState SORT_LEAVES = TFBlocks.sorting_leaves.get().getDefaultState();
    public static final BlockState RAINBOW_LEAVES = TFBlocks.rainboak_leaves.get().getDefaultState();
    public static final BlockState ROOTS = TFBlocks.root.get().getDefaultState();
    public static final BlockState GRASS = Blocks.GRASS.getDefaultState();  
    public static final BlockState TALL_GRASS = Blocks.TALL_GRASS.getDefaultState();  
    public static final BlockState FERN = Blocks.FERN.getDefaultState();
    public static final BlockState TALL_FERN = Blocks.LARGE_FERN.getDefaultState();
    public static final BlockState POPPY = Blocks.POPPY.getDefaultState();
    public static final BlockState DANDELION = Blocks.DANDELION.getDefaultState();
    public static final BlockState RED_TULIP = Blocks.RED_TULIP.getDefaultState();
    public static final BlockState ORANGE_TULIP = Blocks.ORANGE_TULIP.getDefaultState();
    public static final BlockState PINK_TULIP = Blocks.PINK_TULIP.getDefaultState();
    public static final BlockState WHITE_TULIP = Blocks.WHITE_TULIP.getDefaultState();
    public static final BlockState ALLIUM = Blocks.ALLIUM.getDefaultState();
    public static final BlockState AZURE = Blocks.AZURE_BLUET.getDefaultState();
    public static final BlockState ORCHID = Blocks.BLUE_ORCHID.getDefaultState();
    public static final BlockState LILY = Blocks.LILY_OF_THE_VALLEY.getDefaultState();
    public static final BlockState CORNFLOWER = Blocks.CORNFLOWER.getDefaultState();
    public static final BlockState OXEYE = Blocks.OXEYE_DAISY.getDefaultState();
    public static final BlockState MAYAPPLE = TFBlocks.mayapple.get().getDefaultState();
    public static final BlockState FIDDLEHEAD = TFBlocks.fiddlehead.get().getDefaultState();
    public static final BlockState MUSHGLOOM = TFBlocks.mushgloom.get().getDefaultState();
    public static final BlockState FIRE_JET = TFBlocks.fire_jet.get().getDefaultState();
    public static final BlockState SMOKER = TFBlocks.smoker.get().getDefaultState();
    public static final BlockState AIR = Blocks.AIR.getDefaultState();
    public static final BlockState MYCELIUM = Blocks.MYCELIUM.getDefaultState();
    public static final BlockState UBEROUS_SOIL = TFBlocks.uberous_soil.get().getDefaultState();
    public static final BlockState DIRT = Blocks.DIRT.getDefaultState();
    public static final BlockState STONE = Blocks.STONE.getDefaultState();
    public static final BlockState GRASS_BLOCK = Blocks.GRASS_BLOCK.getDefaultState();
    public static final BlockState PODZOL = Blocks.PODZOL.getDefaultState();
    public static final BlockState COARSE_DIRT = Blocks.COARSE_DIRT.getDefaultState();
    public static final BlockState FIREFLY_JAR = TFBlocks.firefly_jar.get().getDefaultState();
    public static final BlockState PUMPKIN = Blocks.PUMPKIN.getDefaultState();
    public static final BlockState DEAD_BUSH = Blocks.DEAD_BUSH.getDefaultState();
    public static final BlockState BROWN_MUSHROOM = Blocks.BROWN_MUSHROOM.getDefaultState();
    public static final BlockState JACK_O_LANTERN = Blocks.JACK_O_LANTERN.getDefaultState();
    public static final BlockState DEADROCK = TFBlocks.deadrock.get().getDefaultState();
    public static final BlockState WEATHERED_DEADROCK = TFBlocks.deadrock_weathered.get().getDefaultState();
    public static final BlockState CRACKED_DEADROCK = TFBlocks.deadrock_cracked.get().getDefaultState();
    public static final BlockState SNOW = Blocks.SNOW_BLOCK.getDefaultState();
    public static final BlockState PACKED_ICE = Blocks.PACKED_ICE.getDefaultState();
    public static final BlockState MUSHROOM_STEM = Blocks.MUSHROOM_STEM.getDefaultState();//.with(HugeMushroomBlock.UP, true).with(HugeMushroomBlock.DOWN, false).with(HugeMushroomBlock.NORTH, true).with(HugeMushroomBlock.SOUTH, true).with(HugeMushroomBlock.WEST, true).with(HugeMushroomBlock.EAST, true);
    public static final BlockState MUSHROOM_CAP_RED = Blocks.RED_MUSHROOM_BLOCK.getDefaultState().with(HugeMushroomBlock.DOWN, false);//.with(HugeMushroomBlock.UP, true).with(HugeMushroomBlock.NORTH, true).with(HugeMushroomBlock.SOUTH, true).with(HugeMushroomBlock.WEST, true).with(HugeMushroomBlock.EAST, true);
    public static final BlockState MUSHROOM_CAP_BROWN = Blocks.BROWN_MUSHROOM_BLOCK.getDefaultState().with(HugeMushroomBlock.DOWN, false);//.with(HugeMushroomBlock.UP, true).with(HugeMushroomBlock.NORTH, true).with(HugeMushroomBlock.SOUTH, true).with(HugeMushroomBlock.WEST, true).with(HugeMushroomBlock.EAST, true);
}
